apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: azfarsec
spec:
  podSelector:
    matchLabels:
      app: azfard
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 80
          protocol: TCP
