apiVersion: v1
kind: Pod
metadata:
  name: "azfarpod3"
  labels:
    region: IN
spec:
  volumes:
    - name: s1
      persistentVolumeClaim:
        claimName: azfarpvc

  containers:
    - name: "myc2"
      image: "vimal13/apache-webserver-php"
      volumeMounts: 
        - mountPath: /var/www/data
          name: s1
